# Generated by Django 4.2.9 on 2024-02-03 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todoapps", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="todo",
            options={"verbose_name": "TODOタスク", "verbose_name_plural": "TODOタスク"},
        ),
        migrations.AlterModelOptions(
            name="todocategory",
            options={
                "verbose_name": "TODOカテゴリ",
                "verbose_name_plural": "TODOカテゴリ",
            },
        ),
    ]
